### ISSUE TITLE
will you release the code?

### ISSUE THREAD

**Issue by xinli2008** [fanfanda/M3DDM#1]
nice job! will you release the project code?

**Comment by fanfanda** [comment]
Thank you for your attention. Considering the commercialization of the model, there are currently no plans to open-source the model parameter files or source code of the project. But currently, you can apply for a Taobao business account and test your own video on the Rubik's Cube (尺寸魔方) [here](https://chuangyi.taobao.com).

**Comment by fanfanda** [comment]
After policy review, we are ready to open-source our model within three months! @xinli2008
