### ISSUE TITLE
about trial method

### ISSUE THREAD

**Issue by haooxia** [fanfanda/M3DDM#2]
Is this the only [channel](https://chuangyi.taobao.com/) that can be used for trial now? However, this [merchant account](https://github.com/fanfanda/M3DDM/blob/main/assets/Tutorial.pdf) seems to require a company to register. Can I try it out if I am a student?

**Comment by fanfanda** [comment]
I will open source the test code and model parameters as soon as possible. Please refer to the update list for details.
