### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by ucasyjz** [fanfanda/M3DDM#3]
Can you show me the details of the inference process, because I see that you  concatenate corrupted raw video latents, random masked video latent, and masks before feeding them into the 3D UNet network in the training stage, but in the inference, thee should do not exist corrupted raw video latents, and the input dimension should change for the  3D UNet network, Does the network structure of the training and reasoning process change，how can this work?

Meanwhile, if you used the pre-trained diffusion model, if the input dimension change after concatenate, how can you feed it to the 
 3D UNet network, is there exist a layer for dimensional transformation

**Comment by fanfanda** [comment]
Randomly sample a noise from the normal distribution, or add noise to the result after inpainting from video frames, for more details please refer to the appendix of our paper. Additionally, our inference code and model files have been made open source.
